create table if not exists endpoints
(
    id        bigint generated by default as identity primary key not null,
    app       varchar(50)                                         not null,
    uri       varchar(100)                                        not null,
    ip        varchar(50)                                         not null,
    timestamp timestamp with time zone                            not null
);
