create table if not exists users
(
    id    bigint generated by default as identity primary key not null,
    name  varchar(20)                                         not null,
    email varchar(40) unique                                  not null
);

create table if not exists categories
(
    id   bigint generated by default as identity primary key not null,
    name varchar(50) unique                                  not null
);

create table if not exists events
(
    id                 bigint generated by default as identity primary key not null,
    compilation_id     bigint,
    annotation         varchar(2000)                                       not null,
    category           bigint references categories (id)                   not null,
    confirmed_requests bigint                                              not null,
    created_on         timestamp with time zone                            not null,
    description        varchar(7000)                                       not null,
    event_date         timestamp with time zone                            not null,
    initiator          bigint references users (id)                        not null,
    lat                float                                               not null,
    lon                float                                               not null,
    paid               boolean                                             not null,
    participant_limit  int                                                 not null,
    published_on       timestamp with time zone,
    request_moderation boolean                                             not null,
    state              varchar(15)                                         not null,
    title              varchar(120)                                        not null,
    views              bigint                                              not null
);

create table if not exists requests
(
    id        bigint generated by default as identity primary key not null,
    created   timestamp with time zone                            not null,
    event     bigint references events (id)                       not null,
    requester bigint references users (id)                        not null,
    status    varchar(20)                                         not null
);

create table if not exists compilations
(
    id     bigint generated by default as identity primary key not null,
    pinned boolean                                             not null,
    title  varchar(100)                                        not null
);

create table if not exists event_compilations
(
    event_id       bigint references events (id)       not null,
    compilation_id bigint references compilations (id) not null
);

